### ISSUE TITLE
Analyzer bug

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1138]
```
CREATE STREAM raw_searches_total
(
  stamp text,
  searches integer
);

CREATE CONTINUOUS VIEW searches_total_10min AS
SELECT
  substring(stamp from 0 for 16) || '0:00' AS stamp,
  sum(searches) AS searches
FROM raw_searches_total GROUP BY stamp;

INSERT INTO raw_searches_total (stamp, searches) VALUES ('2015-08-26 21:00:00', 200);

SELECT * FROM searches_total_10min;
 stamp | searches
-------+----------
(0 rows)
```

http://stackoverflow.com/questions/32229053/pipelinedb-continuous-views-do-not-work

**Comment by usmanm** [comment]
Simplest repro case: 

    CREATE CONTINUOUS VIEW v AS SELECT x::int + 1 FROM stream GROUP BY x;

**Comment by derekjn** [comment]
Woot this has been fixed:

    ERROR:  column "searches_total_10min_mrel.stamp" must appear in the GROUP BY clause or be used

Grouping on the expression then works properly.

**Comment by usmanm** [comment]
The second query is the actual bug. Grouping is allowed if the grouped expression is used in an arithmetic expression which we current fail on:
```
CREATE CONTINUOUS VIEW v AS SELECT x::int + 1 FROM stream GROUP BY x;
```

**Comment by derekjn** [comment]
@usmanm I'm wondering if these are even worth supporting though. The problem is that the combiner plan  doesn't see an arithmetic expression, it just sees the resulting column from the worker query. Supporting this type of query seems like it requires non-trivial work in the analyzer, for a class of query that isn't even used by anyone (purposely).
