### ISSUE TITLE
pipeline-dump should work with continuous views

### ISSUE THREAD

**Issue by Degola** [pipelinedb/pipelinedb#1255]
Hey,

we're not too experienced with postgresql and the following error but with the update to the newest pipelinedb version today we experienced the following error:

FATAL:  database files are incompatible with server
DETAIL:  The database cluster was initialized with CATALOG_VERSION_NO 201508140, but the server was compiled with CATALOG_VERSION_NO 201510270.

We tried to find the pg_upgrade command but it seems that it is not there. The pipeline_dumpall | pipeline method also doesn't work (pipeline_dumpall is looking for pg_dump instead of pipeline_dump which we fixed with a symlink).

The relations for the continuous views and streams have been broken after applying the dumpall method 
to a fresh database directory:
```
analytics=# \d
                                List of relations
 Schema |                        Name                        | Type  |   Owner
--------+----------------------------------------------------+-------+-----------
 public | schema_version                                     | table | sebastian
 public | statistics__installs__daily_mrel0                  | table | sebastian

analytics=# select * from statistics__installs__daily;
ERROR:  relation "statistics__installs__daily" does not exist
```
Are we doing something wrong or is that a bug?

Best,

Seb

**Comment by derekjn** [comment]
Hey @Degola ,

The problem is that the continuous view metadata is not dumped, so it's not being created in the new database. We'll add support for this soon. In the meantime, here's what you can do to work around this:

* Export your `*_mrel0` tables with `pipeline-dump --column-inserts --data-only --table=<*_mrel0> <db name>`
* Create your continuous views in the upgraded database using `CREATE CONTINUOUS VIEW`
* Set `continuous_query_materialization_table_updatable` to `true` in your `pipelinedb.conf`
* Load the exported `*_mrel0` data into your upgraded database

Let us know if that works for you!

**Comment by Degola** [comment]
Hey @derekjn, thanks, we will live with that for now and next upgrade.

**Comment by usmanm** [comment]
Requires support for continuous views and streams in `pg_dump.c:dumpTableSchema`.
