### ISSUE TITLE
New 0.8.5 docker image

### ISSUE THREAD

**Issue by joshk0** [pipelinedb/pipelinedb#1287]
Can we have a push of pipelinedb 0.8.4 to the public docker hub please?

@jberkus

**Comment by usmanm** [comment]
We'll try to get this up today, sorry about that! I've created #1288 so we auto push to docker hub whenever we push out a new release.

**Comment by jberkus** [comment]
Presumably this will replace my manual builds?

**Comment by jberkus** [comment]
or should I push 0.8.4?  I'm building it now ...

**Comment by derekjn** [comment]
@jberkus let's go ahead and push 0.8.4 in the meantime. Thanks!

**Comment by jberkus** [comment]
Had to abort this because 0.8.4 is crashing.  See follow-up issue.

**Comment by joshk0** [comment]
What follow-up issue?

**Comment by usmanm** [comment]
https://github.com/pipelinedb/pipelinedb/issues/1279

**Comment by usmanm** [comment]
I think the problem is that the default shared memory size if 64mb which is pretty small for us. We need to increase it using this build option: https://github.com/docker/docker/blob/master/api/client/build.go#L62. I have Docker 1.9.1 on my machine but it doesn't expose the `-shm-size` parameter. We might have to wait for the next release...

**Comment by usmanm** [comment]
@jberkus: This should be good to go now.
