### ISSUE TITLE
Composite types not working on Continuous views

### ISSUE THREAD

**Issue by saurabhere** [pipelinedb/pipelinedb#1297]
CREATE TYPE my_type
    {
      integerone integer,
      integertwo integer
    };
    CREATE CONTINUOUS VIEW my_view as 
    SELECT val::my_type, count(*) FROM my_stream GROUP BY val;

Outputs:

    ERROR: could not find hash function for hash operator 2988

**Comment by usmanm** [comment]
#1298 should fix this as well.

**Comment by derekjn** [comment]
Hi @saurabhere, we've decided that this is actually correct behavior that yields a non-obvious error message. When grouping, it is necessary to be able to determine equality between two values in order to figure out if they belong to the same group. With custom types, there is no way to know how to correctly determine equality, so now we require equality functions to be associated with each grouping column, which will be reflected in the error message you'll see in the next release.

Obviously in this case we'd assume that `integerone` and `integertwo` being equal would constitute full equality, but that is still subjective and certainly not generalizable. Thanks for your patience here!

**Comment by saurabhere** [comment]
So, Should this work on the current release(8.4) if I add equality function for the composite type?

**Comment by derekjn** [comment]
Yes, that will work. Please let us know if you have any further issues here.

**Comment by saurabhere** [comment]
Sorry, I tried this and this doesn't seem to work. 
Even without creating an equality operator for my_type, queries such as: 
```
CREATE TABLE my_table (id integer, mttype my_type);
INSERT INTO my_table(id, mttype) VALUES (1, '(2,12)') ,(2, '(2,12)') , (3, '(2,13)'), (4, '(2,13)');

SELECT mttype, count(*) FROM my_table GROUP BY mttype;
```
work correctly. 
So I figured, pipelinedb must be using the equality operator somewhere else. So I added the operator.
Here is the code for it:
```
CREATE OR REPLACE FUNCTION my_type_eq(my_type, my_type) RETURNS BOOLEAN LANGUAGE SQL STRICT IMMUTABLE AS 
$$ 
SELECT $1.integerone::integer = $2.integertwo::integer 
AND $1.integertwo::integer = $2.integerone::integer; 
$$;
CREATE OPERATOR = (LEFTARG = my_type, RIGHTARG= my_type, PROCEDURE = my_type_eq);
```
To test this, I used a query somewhat like: 
```
SELECT (t1.mttype).integerone from my_table t1, my_table t2 where t1.mttype = t2.mttype; 
```
which gave no results since the new equality operator compares integerone = integertwo.

Even after this, I get the same error on creating the view. What else is required?

**Comment by derekjn** [comment]
Hi @saurabhere,

You'll need to create an [operator class](http://www.postgresql.org/docs/9.4/static/sql-createopclass.html) for this to work properly, as continuous views internally hash groups. We've updated the error message to be more informative.
