### ISSUE TITLE
Merge 9.5

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1318]
RC1 is out: http://www.postgresql.org/about/news/1631/

**Comment by usmanm** [comment]
And release it as 0.9.0 beta.

**Comment by theory** [comment]
9.5.0 will drop this week. `ON CONFLICT IGNORE` will be a killer feature for Pipeline, I suspect.

**Comment by usmanm** [comment]
@theory: Not sure how. Streams only support insertions and there's no unique index for streams on conflict on.

**Comment by theory** [comment]
Oh. Well that's what I get for just recalling behavior from blog posts I read a couple months ago.

This makes me sad. Was going to look at using Pipeline for time boxed aggregates, but since we get dupes all the time and they need to be filtered out, it sounds like that might not work. (I'll follow up with questions in a more appropriate forum.)

**Comment by usmanm** [comment]
Sorry! Yea, let us know what your use case is and we'll help you figure out if and how PipelineDB can be used for it. Such discussions usually take place on our [Gitter channel](https://gitter.im/pipelinedb/pipelinedb). Talk soon.

**Comment by derekjn** [comment]
This merge should also come with support for `GROUPING SETS`.
