### ISSUE TITLE
Feature request: Seed continuous view on creation

### ISSUE THREAD

**Issue by tothandor** [pipelinedb/pipelinedb#1436]
On creating a continuous view one have to wait as long as the max_age to become usable. If one have to alter the query in the continuous view, or there's a disruption in the stream, than a considerable amount of time is needed to recover.
Streams should have a setting, where one can define a further retention for the events. Also it's only possible if arrival_timestamp could be overridden somehow. For example Flume uses an Avro schema to enable this. See [FlumeEventAvroEventSerializer.java](https://github.com/apache/flume/blob/trunk/flume-ng-core/src/main/java/org/apache/flume/serialization/FlumeEventAvroEventSerializer.java)

**Comment by usmanm** [comment]
@tothandor, you can use any timestamp type column in place of `arrival_timestamp`. However, you can't use `max_age` for that, you'll have to use the explicit condition: `WHERE <ts_column> > clock_timestamp() - interval '1 hour'`. This allows you to back fill the continuous view as well because now you control the time axis for the sliding window. Should this resolve your issue?

**Comment by tothandor** [comment]
Sorry for reacting so late and thanks for you explanation! I did not realized until your reply, that other conditions could also influence retention. Thus there's no need to override arrival_timestamp.

**Comment by usmanm** [comment]
I don't we have that documented, so there's no way you could've known :). I'll update the docs.
