### ISSUE TITLE
issues with rename of config file, default database

### ISSUE THREAD

**Issue by jberkus** [pipelinedb/pipelinedb#1557]
So, the fact that pipelinedb calls its config file pipeline.conf, and its default created database "pipeline", causes issues using general PostgreSQL administration tools with it.  See this issue with Patroni:

https://github.com/zalando/patroni/pull/210

**Comment by derekjn** [comment]
Hey @jberkus! I read through https://github.com/zalando/patroni/pull/210, and there are a couple of options here. I think that the easiest approach is to just run two simple commands on the PipelineDB instance after initializing: 

* `psql -c "CREATE DATABASE postgres"`
* `ln -s $PGDATA/pipelinedb.conf $PGDATA/postgresql.conf`

The other approach which the [PR](https://github.com/zalando/patroni/pull/210) has addressed is obviously to just make patroni configurable, which there seems to be an aversion to because those config options are only ever likely to be used with PipelineDB. I would tend to agree with that view.

The last approach would be for us to change the default database name (or make it configurable), which I don't think makes sense on our side. While we strive to maintain deep compatibility with postgres at the SQL/libpq levels, it is a reality that tools built specifically for postgres may require small tweaks or workarounds to work seamlessly with pipeline, and I think the first approach I outlined falls in to that category.

**Comment by jberkus** [comment]
Makes, sense, closing.
