### ISSUE TITLE
Add union + intersection functions for probabilistic data types

### ISSUE THREAD

**Issue by joshk0** [pipelinedb/pipelinedb#1624]
Is there a way the hll_union function as described [here](https://github.com/aggregateknowledge/postgresql-hll#operators) can be incorporated into PipelineDB easily?

I can work up a PR for this, but if it's already possible using something that's already part of PipelineDB HLL implementation, I'd prefer not to write any code. :)

The operators (|| etc.) would be a bonus.

- [x] `bloom_union(b0, b1)`
- [x] `bloom_intersection(b0, b1)`
- [x] `hll_union(h0, h1)`

**Comment by usmanm** [comment]
Yes, that should be fairly simple. I should probably add union + intersection functions for all probabilistic data types.

**Comment by andrewshi94** [comment]
Hey Team - is there any new on this? We would love to have this feature!

**Comment by usmanm** [comment]
Hey @andrewshi94, sorry we've had our hands full with other stuff and haven't gotten the chance to work on this. All the functionality is already implemented, just need to add some catalog entries and maybe create a couple of wrapper functions. If you guys wanna take a stab at it, I'd be happy to put you in the right direction? Otherwise, unfortunately I don't think we're going to have any free cycle for the next few weeks...

**Comment by derekjn** [comment]
I'll spend some cycles getting this into the next release. Off the top of my head, HLL intersections aren't possible, although we can estimate the cardinality of an HLL intersection with MinHash (#697).

**Comment by andrewshi94** [comment]
Thanks guys!!
