### ISSUE TITLE
Deadlock in combine_table

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1678]
https://circleci.com/gh/pipelinedb/pipelinedb/5595?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by derekjn** [comment]
From the PR:

> We can't release the lock early. I tried with a `RowExclusiveLock` but that doesn't work because the order in which we acquire the tuple locks might conflict with the combiner. So we need to keep it for the duration of the combine operation. We might have to be a little more surgical here.

**Comment by derekjn** [comment]
After thinking through some approaches to fixing this, it just seems kind of messy to update a matrel from a proc outside of a combiner because it violates a pretty fundamental assumption our design makes: any matrel row will only ever be updated by one process.

An alternative approach is to simply write all the input table's rows into the combiners as if they're groups coming from workers. Obviously this can cause increased congestion, but matrel lock contention will ultimately have a similar effect anyways. @usmanm thoughts?

**Comment by derekjn** [comment]
The obvious downside to using the above approach is that it's not transactional, which is kind of a huge downside. I think not releasing this lock will also work:

https://github.com/pipelinedb/pipelinedb/blob/master/src/backend/pipeline/cont_combiner.c#L472

Releasing that lock makes it possible for the combiner to have a lock on the matrel tuple but not on the matrel itself, which is the core problem here.

**Comment by usmanm** [comment]
We definitely shouldn't be releasing that lock then.
