### ISSUE TITLE
Drop stream&continuous view  problem.

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1728]
I test create continuous view .

create stream str(x bigint,y text,z timestamp);

pipeline=# create table t(x text);
insert into t select 'create continuous view cv_'||generate_series(1,2000)||' as select x,y,z from str;';

copy t to '/home/pipeline/a.csv';
\i /home/pipeline/a.csv;
ERROR:  maximum number of continuous queries exceeded

One stream  target continuous view just 1000?

I try to drop stream&cv

pipeline is corrupted...

drop cascades to continuous view cv_73
and 923 other objects (see server log for list)

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
!> \q 

detail log:
12575 LOG:  database system is ready to accept connections
12576 LOG:  continuous query scheduler started
12577 LOG:  starting continuous query processes for database: "pipeline"
12578 LOG:  autovacuum launcher started
12579 LOG:  continuous query process "combiner0 [pipeline]" running with pid 69843
12580 LOG:  continuous query process "worker0 [pipeline]" running with pid 69844
12581 LOG:  backend pid is 69850
12582 LOG:  server process (PID 69850) was terminated by signal 9: Killed
12583 DETAIL:  Failed process was running: drop stream str cascade;

**Comment by usmanm** [comment]
PipelineDB currently has a hard limit on the number of continuous queries, which is 1023 I believe. I will look at your query and see why it's making the server crash though.

**Comment by derekjn** [comment]
The issue was that with a drop that cascades to many objects, there are a lot of `UpdatePipelineStreamCatalog` calls, which allocates quite a bit of memory due to query parsing:

![massif](https://cloud.githubusercontent.com/assets/384666/21473511/5b830fd2-cac3-11e6-8fe1-99ded9ebe45c.png)

All of these calls happen in one transaction, which can obviously accumulate excessive memory.

`UpdatePipelineStreamCatalog` now aggressively frees everything before returning. Note that there's still a hard limit of `1024` on the maximum number of continuous views, defined at compile time by `MAX_CQS`. @sangli00 if you need a higher limit you can compile with that `#define` overridden, or if you have an actual use case for that many CVs we can look at increasing the limit, although it hasn't ever been an issue.

**Comment by sangli00** [comment]
nice,I think `MAX_CQS`  used GUC parameter is good.  maybe sometime need create more CV.
