### ISSUE TITLE
Feasibility of beginning to use pipelinedb right now?

### ISSUE THREAD

**Issue by zachdaniel** [pipelinedb/pipelinedb#1801]
I've noticed a lot of issues that illustrate the amount of changes that pipelinedb is undergoing right now. How stable are things? Would you recommend waiting until the postgres extension refactor is done? Our use case is a mission critical production application.

Any thoughts?

**Comment by derekjn** [comment]
@zachdaniel we would not recommend waiting until the extension refactor is done to start using PipelineDB. The extension refactor doesn't fundamentally involve stability, it's mostly a matter of restructuring existing code and most of our code has always been in its own modules anyways (`src/backend/pipeline`).

In fact, the main reason for beginning the extension refactor recently was because PipelineDB has reached  a fairly high degree of stability. We have quite a few large production deployments (that we know about, probably more that we don't know about), many of which are paying customers of ours, and some of those customers are in the Fortune 500.

If you would like to discuss your use case in more detail and get our perspective on it specifically, please feel free to email us!
