### ISSUE TITLE
stream count(distinct value) seem not work well?

### ISSUE THREAD

**Issue by Tim201706** [pipelinedb/pipelinedb#1813]
Hi,some question about stream count(distinct value);
when  I create table and count(distinct val)  =1000  is correct;
create table t1(id int, val character varying);
insert into t1 select 3,generate_series(1,1000);

pipeline=# select id,count(distinct val) from t1 group by id;
 id | count 
----+-------
  3 |  1000
(1 row)

when use STREAM count(distinct value)=1006;
CREATE STREAM s1 (id int, val character varying);    
CREATE CONTINUOUS VIEW cv1 AS    
SELECT id,count(distinct val) FROM s1 GROUP BY id;    

insert into s1 select 3,generate_series(1,1000);

pipeline=# select * from cv1;
 id | count 
----+-------
  3 |  1006
(1 row)

How can I use STREAM  count(distinct val)  =1000  or STREAM not support this?

version pipelinedb-0.9.7u4-centos6-x86_64.rpm
pipeline=# select version();
                                                 version                                                  
----------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17), 64-bit
(1 row)

**Comment by derekjn** [comment]
@Tim201706 Thanks for the helpful writeup! 

[counting distincts on streams](http://docs.pipelinedb.com/aggregates.html#general-aggregates) uses [HyperLogLog](http://docs.pipelinedb.com/probabilistic.html#hyperloglog) in order to only consume constant space on theoretically infinite streams, with the tradeoff obviously being a small margin of error. Empirically it is about 99.2% accurate.

If you really want exact distinct counts on a stream, we do provide the [exact_count_distinct](http://docs.pipelinedb.com/aggregates.html#miscellaneous-aggregates) aggregate, it goes without saying that it should be used on streams with careful consideration about your expected workload

Keeping track of unique values with perfect accuracy unavoidably involves storing all unique values seen, so please keep that in mind that each `count` column of your CV will ultimately be storing all of this information internally when using `exact_count_distinct`.

Please let us know if you have any further issues here.
