### ISSUE TITLE
Custom trigger function using pg_notify

### ISSUE THREAD

**Issue by brettlaforge** [pipelinedb/pipelinedb#1816]
I'd like to notify my application when a specific condition is met in a CV. I'm attempting to execute a custom trigger function that will run 'pg_notify' where my application is listening.

```
CREATE OR REPLACE FUNCTION notify()
    RETURNS trigger AS
    $$
    BEGIN
        INSERT INTO t (ts, key, value) VALUES (NEW.ts, NEW.key, NEW.value);
        PERFORM pg_notify('trigger', (NEW.value)::text);
        RETURN NEW;
    END;
    $$
    LANGUAGE plpgsql;

CREATE TABLE t (
    ts timestamp,
    key varchar(255),
    value int
);

CREATE STREAM IF NOT EXISTS s (
    x int
);

CREATE CONTINUOUS VIEW s_cv AS
    SELECT
        SUM(x) AS sum
    FROM s;

CREATE CONTINUOUS TRANSFORM s_cv_ct AS
    SELECT
        arrival_timestamp AS ts,
        's_cv'::varchar AS key,
        (new).sum AS value
    FROM output_of('s_cv')
    THEN EXECUTE PROCEDURE notify();

INSERT INTO s (x) VALUES (10);
```

In the above example, the 't' table contains a row for each update to the s_cv as expected but the notification is not send immediately. Interestingly if you open a client at run 'NOTIFY trigger;', it will flush all the notifications pending and they will then appear.

I believe this question was asked in #1654 and if I understand the problem correctly, the pg_notify does not work in a CT because the CT runs in a bgworker whereas the clients are in a different process. A related issue also discusses using a COPY statement to receive the events from an output stream.

If it still is the case the pg_notify is not possible from a CT, I was hoping you guys could shed some light on this and the current state of pubsub within pipelinedb and how one would go about notifying an application when a condition is met in a CV.

**Comment by derekjn** [comment]
@brettlaforge You are correct about #1654. And I believe this is actually the expected behavior with `NOTIFY` and not necessarily something we chose not to support. Its semantics are actually non-intuitive in many cases, such as messages not being "pushed" to listening clients. `LISTEN/NOTIFY` actually wasn't really designed for pubsub, but moreso for things like notifying clients when a table changed *at some point before they use it again*, but not necessarily in real time.

Anyways, there currently isn't any built-in support for pubusb in PipelineDB as there hasn't been much demand for it and it's a pretty big problem to get right. Your best bet is probably going to be to write some kind of trigger function that does exactly what you want. This is probably easier than you might think, and we'd be happy to give you feedback on your approach if you decide to take this route.

For example, [Stride](https://www.stride.io/) uses Redis for pubusb. We have transforms that consume output streams, and simply publish the rows to a Redis pubsub channel, and subscribers simply consume this channel. It's probably less than 100 lines of C code and has worked pretty well for us.

Introducing a new dependency obviously might be a heavyweight solution for you, but I just wanted to let you know how we're solving this problem ourselves. Hopefully that was helpful, and please let us know if you need any more insight on anything!

**Comment by brettlaforge** [comment]
Thanks you so much. I appreciate the insight into Stride and how you've handled this problem there. I think the added dependency of Redis is acceptable. I'll see if I can get anywhere with a custom C extension, I've never written one so I'm sure it will be a challenge, maybe I can find some example of someone sending messages from PostgreSQL to Redis online.

**Comment by brettlaforge** [comment]
My custom C extension so far: https://github.com/brettlaforge/pg_redis_pubsub

**Comment by nuhamind2** [comment]
I wish i read this issue first
