### ISSUE TITLE
Question: what is the most significant advantage of pipelinedb over sql server trigger? 

### ISSUE THREAD

**Issue by 50hz** [pipelinedb/pipelinedb#1862]
at the moment I am using SQL Server trigger to build a "continuous" view, which is working most of the time. I know pipeline only store the "view" data but this can be achieved quite easily with some regular cleanup on the "raw table" that invoke the trigger. so I am sure I misunderstand some important use case of pipelinedb. 

much appreciated if anyone can give me some hits or more specific use case that would have been much difficult to achieve with SQL Server triggers? 

thanks

**Comment by derekjn** [comment]
@50hz can you clarify what you mean by this?

> at the moment I am using SQL Server trigger to build a "continuous" view

My impression is that you probably aren't doing high-throughput aggregation with SQL server, which is the kind of workload PipelineDB is designed for. Since PipelineDB only stores the *aggregate* output of continuous views, it enables extremely high aggregation performance without **ever having to write any granular data to disk**. Only aggregate values are incrementally updated after performing as much aggregation in memory as possible on incoming microbatches of events.

For sustained workloads ingesting thousands, hundreds of thousands, or millions of events per second, writing those events to a table is usually not even feasible, even if it's being periodically cleaned up as you mentioned.

So in general, if you're not doing high-throughput aggregation then you probably don't need PipelineDB.

**Comment by 50hz** [comment]
@derekjn thanks! it is a very good answer!
