### ISSUE TITLE
Reuse aggregate continuous view

### ISSUE THREAD

**Issue by zxding** [pipelinedb/pipelinedb#1954]
How should I do if I wanna reuse one aggregate continuous view as another stream input?
For example:
       Create continues view test_view as select a,b,max(c),sum(d) from test_stream group by 1,2;
       insert into test_stream(1,1,0,0) (1,1,1,0)(1,1,2,0)(1,1,3,0)(1,1,4,0)
       insert into test_stream(1,2,0,0) (1,2,1,0)(1,2,2,0)(1,2,3,1)
       insert into test_stream(2,3,0,0)(2,3,1,0)(2,3,2,0)(2,3,3,0)(2,3,4,0)(2,3,5,0)
       insert into test_stream(2,4,0,0)(2,4,1,0)(2,4,2,0)(2,4,3,0)(2,4,4,0)(2,4,5,0)(2,4,6,0)

if I run select * from test_view then I will get result as following
     a b max sum
     1 1  4       0
     1 2  3       1
     2 3 5        0
     2 4 6       0
@view2

Further,if I run "select a ,max(max) from view2 where sum=0 group by a"
,then the result as following 

   1 4
   2 6
it is the the final result I want.

because having count(1)>n is not support, and I think use (New) from output_of('test_view') is also not good idea.
Any suggestion?

**Comment by derekjn** [comment]
Hi @zxding!

What you probably want to use are [delta streams](http://docs.pipelinedb.com/streams.html#delta-streams) and/or [output streams](http://docs.pipelinedb.com/streams.html#output-streams):

```sql
CREATE STREAM s (x integer);
CREATE CONTINUOUS VIEW v0 AS SELECT day(arrival_timestamp), count(DISTINCT x) FROM s GROUP BY day;

-- "Down" aggregate daily distincts count to month without losing any information
CREATE CONTINUOUS VIEW v1 AS SELECT month(combine((delta).count) FROM output_of('v0') GROUP BY month;
```

Does that help?

**Comment by zxding** [comment]
@derekjn 
Thank you for reply so soon.
I will try your suggestion, but I am still confused about the usage on "combine", "delta"  ,"old" ,"new" even I have read demo on doc several times. Would you please give me a more intuitionistic demo to explain it, or maybe you can give me a link where you already explained.
Thank you so much.

**Comment by derekjn** [comment]
@zxding sure, an output stream will contain all incremental changes made to a CV. It has three rows, which are as follows:

* `new`  - Latest version of the row
* `old` - Previous version of the row
* `delta` - `new` - `old`, basically the "diff"

As an example, consider the following setup:

```sql
CREATE FOREIGN TABLE s (x integer) SERVER pipelinedb;
CREATE VIEW v0 AS SELECT count(*), sum(x) FROM s;

-- This CV will keep track of the `new`, `old`, and `delta` rows so that we can examine them
CREATE VIEW output AS
 SELECT (old), (new), (delta) FROM output_of('v0');
```

Now, if we write one row to the stream `s`:

```sql
INSERT INTO s (x) VALUES (100);
```

The CV will now look like this:

```
postgres=# SELECT * FROM v0
 count | sum 
-------+-----
     1 | 100
(1 row)
```

And here are the output stream rows that we captured based on this row being written:

```
postgres=# SELECT old, new, delta FROM output;
 old |   new   |  delta   
-----+---------+----------
     | (1,100) | (1,100,)
```

The `old` row is `NULL` because it was the first write made to that row. The `new` row is the latest version of the row, and the `delta` row means we increased the `count` by `+1`, and the `sum` by `+100`.

Writing another event to the stream:

```sql
INSERT INTO s (x) VALUES (10);
```

Gives us a CV that looks like this:

```
postgres=# SELECT * FROM v0
 count | sum 
-------+-----
     2 | 110
(1 row)
```

And a new output stream row:

```
postgres=# SELECT old, new, delta FROM output;
   old   |   new   |  delta   
---------+---------+----------
         | (1,100) | (1,100,)
 (1,100) | (2,110) | (1,10,)
```

Now you can see we have an `old` row this time since an `UPDATE` was performed. And the `delta` row now shows that we increased the `count` by `+1` again, and the `sum` by `+10` this time.

I hope this has clarified things for you--please feel free to reopen this issue if you have any further questions. Thanks @zxding!
