### ISSUE TITLE
osx release

### ISSUE THREAD

**Issue by li1** [pipelinedb/pipelinedb#1961]
Hi @derekjn!

Is there already a 1.0 release available for osx that doesn't require building from source?

**Comment by derekjn** [comment]
@li1 yes! We'll publish OSX packages within the next day or so, as well as a Docker image. Our apologies for not publish the OSX binaries just yet, we're in it though and I'll reply here as soon as they're available.

**Comment by li1** [comment]
Hi @derekjn, since it has been over a month now, I was wondering whether the osx binaries are still something that will be released in the near future?

**Comment by derekjn** [comment]
@li1 apologies for the delay here--we've been insanely busy with onboarding new customers after the extension release. We're aiming to get this out this coming week. The reason we haven't made it part of our automated release pipeline yet is that installing packaged extensions on OSX is a bit tricky because there is no standard PG installation on OSX like there is on all other supported platforms. So it requires examining the environment in order to put the extension files in the correct location.

We'll probably end up packaging OSX binaries as a tarball, which you'll then be able to install against your PG installation like so:

```sh
tar -xvf pipelinedb-postgresql-11-1.0.0.tar.gz
cd pipelinedb-postgresql-11-1.0.0
./install.sh
```
Thanks for your patience @li1, we're on it!

**Comment by derekjn** [comment]
@li1 OSX packages are now available as tarballs in our release archives:

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-9

* `pipelinedb-postgresql-10-1.0.0-9.osx.tar.gz`
* `pipelinedb-postgresql-11-1.0.0-9.osx.tar.gz`

Please see installation instructions here:

http://docs.pipelinedb.com/installation.html#macos-osx

Thank you again for your patience here @li1, and please let us know if you have any issues running on macOS/OSX!

**Comment by wenerme** [comment]
No more osx.tar.gz  after 1.0.0-9 release ?
