### ISSUE TITLE
BeginStreamModify/GetMyContQueryDatabaseMetadata system startup race condition 

### ISSUE THREAD

**Issue by amitlan** [pipelinedb/pipelinedb#1963]
Firstly, congratulations on 1.0 release!

The following code in `BeginStreamModify` can crash.  In fact, I observed one by random chance (may have to do with the scheduler bgworker process disappearing or something, the reason of which I'm not sure of.)

```
    else
    {
        sis->db_meta = GetMyContQueryDatabaseMetadata();
        sis->start_generation = pg_atomic_read_u64(&sis->db_meta->generation);
```

I noticed that `GetMyContQueryDatabaseMetadata()` is coded as follows:

```
/*  
 * GetContQueryDatabaseMetadata
 */ 
ContQueryDatabaseMetadata *
GetContQueryDatabaseMetadata(Oid db_oid)
{
    bool found;

    ContQueryDatabaseMetadata *db_meta =
        (ContQueryDatabaseMetadata *) hash_search(
            ContQuerySchedulerShmem->db_table, &db_oid, HASH_FIND, &found);
    
    if (!found)
        return NULL;

    return db_meta;
}   
    
ContQueryDatabaseMetadata *
GetMyContQueryDatabaseMetadata(void)
{
    static ContQueryDatabaseMetadata *db_meta = NULL;

    if (!db_meta)
        db_meta = GetContQueryDatabaseMetadata(MyDatabaseId);
    
    return db_meta;
}
```

Note that `GetMyContQueryDatabaseMetadata` may end up returning `NULL`, so the 2nd line of the following aforementioned code in `BeginStreamModify` may segfault.

```
        sis->db_meta = GetMyContQueryDatabaseMetadata();
        sis->start_generation = pg_atomic_read_u64(&sis->db_meta->generation);
```

Maybe, `GetMyContQueryDatabaseMetadata`  should error out if it couldn't secure a value for `db_meta`, giving appropriate error.

I was hoping to put together a reproducible test case, but upon re-initializing the cluster, I couldn't get it to crash again, but I think the above code suggestion makes sense regardless.

**Comment by derekjn** [comment]
@amitlan so what we decided to do here is simply cause stream `INSERTs` to fail with a helpful message if they are attempted before all PipelineDB worker processes have not started up yet for the first time. This is a fairly unlikely scenario and we feel that explicitly failing here is better than the alternative approach, which would be to silently block until all workers have started up.

The reason the latter approach wasn't taken is because in some cases, `NULL` metadata may indicate a problem with worker configuration/startup (e.g. if `max_worker_processes` has been set too small) so we felt that failing fast here is more helpful.

We'll be pushing out a `1.0.0` release update shortly containing this fix. Thank you so much for your thoughtful investigation on this!

**Comment by amitlan** [comment]
Great, thank you!  I agree that failing with error is the better alternative.
