### ISSUE TITLE
Support for CREATE OR REPLACE VIEW syntax for continuous views

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1967]
If a continuous view create script includes `OR REPLACE` and is re-run, postgres returns an error that the relation already exists. Can the `OR REPLACE` syntax be supported for all PipelineDB entities (streams, views etc) now that it's an extension ?
 
```
CREATE OR REPLACE VIEW wiki_stats WITH (action=materialize) AS
SELECT hour, project,
        count(*) AS total_pages,
        sum(view_count) AS total_views,
        min(view_count) AS min_views,
        max(view_count) AS max_views,
        avg(view_count) AS avg_views,
        percentile_cont(0.99) WITHIN GROUP (ORDER BY view_count) AS p99_views,
        sum(size) AS total_bytes_served
FROM wiki_stream
GROUP BY hour, project;
```

`ERROR: relation "wiki_stats" already exists`

**Comment by derekjn** [comment]
@andrew-blake so we've thought about this and there is a pretty specific reason behind why we don't do it: continuous view definitions can't be modified, and that's really what the semantics of `CREATE OR REPLACE` are.

For example, running `CREATE OR REPLACE` on a regular view over a table just creates a new view query to execute on that table's data, pretty straightforward.

But if we were to do this on continuous views, we'd have to drop the original continuous view and replace it with a new one. All of the materialization table data would be gone. This is a bit more implicit than we generally like to get, especially considering that the result of a mistake due to not understanding the difference in semantics between `CREATE OR REPLACE` on a CV versus a regular view would be complete loss of data.

The same is ultimately true for streams, which can only be modified by adding new columns to them. All continuous queries reading from a stream depend on its schema, so replacing their definition is extremely complex at a minimum and impossible on most cases.

**Comment by andrew-blake** [comment]
Thanks for the detailed explanation. 

Is it possible to raise an error if someone tries using the replace option rather than silently ignoring it?

**Comment by derekjn** [comment]
@andrew-blake yes we can probably do that pretty easily and I think makes sense.

**Comment by derekjn** [comment]
https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0rev2

**Comment by esatterwhite** [comment]
@derekjn Was support for this added?
I get errors with both `REPLACE` and `CREATE OR REPLACE`

**Comment by esatterwhite** [comment]
Would it be possible to deactive / drop and add in response to a replace statement?
Basically the steps on has to do manually?

**Comment by derekjn** [comment]
@esatterwhite no this hasn’t been added yet. And the ‘DROP/CREATE’ behavior wouldn’t give us exactly what is wanted here. The idea of ‘CREATE OR REPLACE’ would be to redefine the CV without losing data.
