### ISSUE TITLE
Postgres regression test failures with PipelineDB enabled

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1980]
I've just run the Postgres regression test suite with and without the PipelineDB extension enabled and am seeing many errors. Regression diffs attached.

[postgresql-10.5-regression.diffs.zip](https://github.com/pipelinedb/pipelinedb/files/2534151/postgresql-10.5-regression.diffs.zip)

I wouldn't have expected there to be any unexpected ERRORs. There are also other regression differences too. 

Summary of the ERROR types below.

```
! ERROR:  relation "constraint_not_exist" does not exist
! ERROR:  relation "doesnt_exist_ft1" does not exist
! ERROR:  relation "doesnt_exist_tab" does not exist
! ERROR:  relation "__onek_unique1" does not exist
! ERROR:  relation "__tmp_onek_unique1" does not exist
! ERROR:  relation "tt8" does not exist
! ERROR:  unrecognized node type: 1953392993
! ERROR:  Upper-level Aggref found where not expected
! ERROR:  Upper-level GROUPING found where not expected
! ERROR:  Upper-level Var found where not expected
```

This is how I ran the regression tests with PipelineDB enabled.

`postgres:/tmp/postgresql/src/test/regress$ EXTRA_REGRESS_OPTS="--loadextension pipelinedb" make installcheck`

A simple example of one of the errors below:

```
postgres=# create database testdb;
CREATE DATABASE

postgres=# \c testdb
You are now connected to database "testdb" as user "postgres".

testdb=# create table if not exists int4_tbl (f1 integer);
CREATE TABLE

testdb=# select * from (values(1)) x(lb), lateral (select lb from int4_tbl) y(lbcopy);
 lb | lbcopy
----+--------
(0 rows)

testdb=# create extension pipelinedb;
CREATE EXTENSION

testdb=# select * from (values(1)) x(lb), lateral (select lb from int4_tbl) y(lbcopy);
ERROR:  Upper-level Var found where not expected
```

**Comment by andrew-blake** [comment]
Btw, this is new in 1.0.0rev3

**Comment by derekjn** [comment]
@andrew-blake again, thank you! A couple of notes here:

* The last few changes to the `combine` aggregate analyzer have created some unintended interactions with queries that it doesn't need to analyze, causing these regression conflicts
* Some (4) vanilla PG tests are expected to fail with PipelineDB loaded and created. The reason is that when PG tests things like its foreign server infrastructure and makes assertions about which foreign servers/FDWs should be present, it doesn't expected to see PipelineDB's foreign server/FDW objects but they're there. We'll be working with the PG team to ideally make these tests more tolerant of being run when extensions are loaded. The same is true for a few of PipelineDB's aggregates, which use polymorphic signatures that break some PG tests that assume standard PG aggregates are the only ones with such signatures. For now, our test infrastructure skips them.
* The remaining test failures were legitimate and have been resolved. The vast majority of PipelineDB users are primarily running PipelineDB on their PG installation, and the test failures you discovered were only relevant to relatively obscure PG queries (testing the limits of query coverage) that aren't relevant to PipelineDB and thus have not been problematic. Obviously it's a bug on our end to break such tests though, and thus they've been relatively straightforwardly resolved.

We'll publish a package revision shortly--thank you so much for your writeups, you are currently the PipelineDB MVP :)

**Comment by derekjn** [comment]
https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0rev4

**Comment by andrew-blake** [comment]
1.0.0rev4 has fixed those ERRORs for me. Thanks for such a quick turnaround!
