### ISSUE TITLE
Specifying compression for tdigest column

### ISSUE THREAD

**Issue by vmihailenco** [pipelinedb/pipelinedb#1982]
E.g. following creates a table with tdigest column

```sql
create table my (id int, td tdigest);
```

Is there a way to specify compression? I've tried `tdigest(20)` but it does not work...

**Comment by derekjn** [comment]
@vmihailenco `tidgests` are generally designed to be built using the [dist_agg](http://docs.pipelinedb.com/aggregates.html#distribution-aggregates) aggregate, which has a signature that allows you to specify a compression:

```sql
CREATE VIEW v0 AS SELECT dist_agg(expr, 200) FROM stream;
```

**Comment by vmihailenco** [comment]
Yes, I already store tdigests in PostgreSQL in `bytea` column for each hour and aggregate tdigests on the client. So I am trying to check if I am able to replace `bytea` with `tdigest` and aggregate tdigests using PipelineDB extension:

```sql
SELECT dist_merge_agg(tdigest_column) from my_table;
```

Does that make sense?

Also what is the best place to learn about PipelineDB binary representation of tdigest? Currently I am using [Golang](https://github.com/caio/go-tdigest/blob/master/serialization.go#L16-L58) which is more or less standard way to serialize tdigests. Java/Ruby has similar implementations...

**Comment by derekjn** [comment]
> Yes, I already store tdigests in PostgreSQL in bytea column for each hour and aggregate `tdigests` on the client.

@vmihailenco wow, that's very interesting! So you're currently using plain `bytea` in PostgreSQL for this (with complex `tdigest` manipulation logic performed in the application) and are looking at doing it with PipelineDB since it has builtin support for these kinds of operations within the database?

Your `dist_merge_agg` call makes sense for combining multiple `tdigests`.

Also, if there is a function that you need here with respect to `tdigest` management and we don't have it, please let us know and we'll very likely be able to add it for you relatively easily. We do that pretty often (that's where most of our functionality comes from!) and it's usually trivial for us to do. We just try not to add anything until users ask for it :)

In terms of `tdigest` serialization in PipelineDB, here's the actual `struct` we use:

https://github.com/pipelinedb/pipelinedb/blob/master/include/tdigest.h#L22

It is a PostgreSQL `varlena` `struct`, which is the format that all variable-length types use in PostgreSQL. `varlena` `structs` are essentially packed `structs` with a header that encodes its length. Everything in a `varlena` `struct` is stored in a single contiguous chunk of memory (e.g. no pointers to anything outside the memory allocated for the `struct`).

And serializing it into a "flat" `bytea` is performed by compressing it:

https://github.com/pipelinedb/pipelinedb/blob/master/src/tdigest.c#L177

I hope that was helpful!
