### ISSUE TITLE
pipelinedb not support where filter in cv?

### ISSUE THREAD

**Issue by darkz1984** [pipelinedb/pipelinedb#2004]
I use postgresql 10.5 and pipelinedb 1.0.0.
I create a stream 
`create FOREIGN table sdk_app_start(
    account_id varchar(200),
    account_name varchar(200),
    account_type varchar(200),
    ad_channel varchar(200),
    ad_id varchar(200),
    ad_subchannel varchar(200),
    ad_type varchar(200),
    android_id varchar(200),
    app_ver varchar(200),
    channel_name varchar(200),
    client_time varchar(200),
    dev_brand varchar(200),
    dev_imei varchar(200),
    dev_language varchar(200),
    dev_lat varchar(200),
    dev_lon varchar(200),
    dev_mac varchar(200),
    dev_model varchar(200),
    dev_os varchar(200),
    dev_os_custom varchar(200),
    dev_osver varchar(200),
    dev_osver_custom varchar(200),
    dev_res varchar(200),
    dev_uuid varchar(200),
    from_ch varchar(200),
    ip varchar(200),
    log_type varchar(200),
    network_type varchar(200),
    pkg_name varchar(200),
    product_id varchar(200),
    record_id varchar(200),
    record_time varchar(200),
    sdk_name varchar(200),
    sdk_ver varchar(200),
    session_id varchar(200),
    source_name varchar(200),
    start_type varchar(200),
    third_account_id varchar(200),
    third_account_name varchar(200),
    timestamp varchar(200),
    user_ip varchar(200),
    receive_time timestamp
) SERVER pipelinedb;`

and
create two cv:
`create view sdk_app_start_result_daily
as
select 
	date(receive_time) action_date
    ,product_id
    ,ad_channel
    ,channel_name
    ,ad_subchannel
    ,ad_id
    ,count(distinct dev_imei) dev_count
    ,sum(1) start_count
from
    sdk_app_start
group by product_id,ad_channel,channel_name,ad_subchannel,ad_id,date(receive_time)
;`

and
`create view sdk_app_start_result_today
as
select 
	date(receive_time) action_date
    ,product_id
    ,ad_channel
    ,channel_name
    ,ad_subchannel
    ,ad_id
    ,count(distinct dev_imei) dev_count
    ,sum(1) start_count
from
    sdk_app_start
where (date(receive_time)=current_date)
group by product_id,ad_channel,channel_name,ad_subchannel,ad_id,date(receive_time)
;
`
but when I insert data into the stream, I can see query result of 
`select * from sdk_app_start_result_daily`

but no data return from the quert

`select * from sdk_app_start_result_today`

So, pipelinedb not support where filter of cv???

**Comment by derekjn** [comment]
Hi @darkz1984,

I believe the issue here is that you're using `current_date`. This expression will only be evaluated once at the beginning of a transaction, so it's effectively a constant that never changes after you've initially defined the CV.

To use a date expression that will always evaluate to the latest time, you can use `clock_timestamp`. And if you only want the date component, replace `current_date` with `date(clock_timestamp())`.

That should resolve the issue here!

**Comment by darkz1984** [comment]
I will try that later

**Comment by darkz1984** [comment]
I have try 
`
create view dh_platform_click_result_today as
select
    date(arrival_timestamp) action_date
    ,"Adid"
    ,count(distinct userip) uv
    ,sum(1) pv
    from dh_platform_click_log
    where date(arrival_timestamp)>=date(clock_timestamp())
group by date(arrival_timestamp),"Adid"
;
`
But it returns me an error:
`
ERROR:  sliding window expressions must look like <timestamp column> > clock_timestamp() - <interval>
`

**Comment by derekjn** [comment]
@darkz1984 one somewhat unrelated note here: `date(arrival_timestamp) >= date(clock_timestamp())` will never evaluate to `true` because `arrival_timestamp` is essentially assigned from `clock_timestamp()`, and that assignment will always happen before your expression is evaluated so it will always evaluate to `false`.

As for the error, so the analyzer thinks you're trying to defining a [sliding window](http://docs.pipelinedb.com/sliding-windows.html) CV. One thing you can do here that may even be more useful for you is putting a [transform](http://docs.pipelinedb.com/continuous-transforms.html) in front of any CVs that need to read only rows matching your condition:

```sql
CREATE VIEW xform WITH (action=transform) AS
 SELECT x, y, ... FROM stream WHERE <condition>
```

And then all of your CVs just read from that transform's [output stream](http://docs.pipelinedb.com/streams.html#output-streams):

```sql
CREATE VIEW cv WITH (action=materialize) AS
  SELECT x, y, ... FROM output_of('xform')
GROUP BY x, y, ...
```
