### ISSUE TITLE
Figure out what license to use

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#890]
http://choosealicense.com/

**Comment by KrishnaPG** [comment]
Wondering what is the implication of this https://github.com/pipelinedb/pipelinedb/issues/777 

Also, please clarify your stand on building closed-source proprietary products that use this DB as backend. Would you consider it as violation of GPL?

**Comment by derekjn** [comment]
Hi @KrishnaPG,

What constitutes a violation of the GPLv3 isn't up to us; it's encoded fairly explicitly in the license itself. In general, if you make any modifications to PipelineDB, the derivative work must be distributed under the same license. If you link to PipelineDB's code, the resulting binary is considered a derivative work and must also be distributed under the same license.

**Comment by KrishnaPG** [comment]
Thanks. 

Usually utilizing a database as backend does not violate the GPL, one of the reasons why databases, such as MongoDB, can afford to choose GPL variants to their core, while releasing the drivers under Apache (Ref: https://www.mongodb.com/community/licensing ).

The reason behind my question is to understand the motivation / strategy behind pushing this DB to GPL.

You have made an interesting remark: "...If you link to PipelineDB's code, the resulting binary is considered a derivative work..."

So, is this a mandatory requirement: that every application has to mandatorily link to the PipelineDB (which then makes it possible to build only GPL applications on top this DB)

or do you offer the possibility to build applications without having to directly link to the PipelineDB (such as the MongoDB model), thus making it possible to build closed source applications.

I agree with your statement: "What constitutes a violation of the GPLv3 isn't up to us"  - but you always have a choice to force the the violation (such as forcing to link the code) or provide workarounds (such as the MongoDB style). 

My intention is to understand your end-goal and licensing strategy, so that I can help my customer make a decision whether to adapt this DB or stay away from it.

**Comment by derekjn** [comment]
Using PipelineDB as a backend without modification does not violate the GPLv3.

And no, nothing is required to link to PipelineDB to use it. Linking in this context generally means "combining" a binary with the GPL'd PipelineDB binary. The resulting binary would have to be GPL'd as well, but this is a fairly unlikely use of any database, including PipelineDB. Building on your MongoDB analogy, PipelineDB is designed to work with all PostgreSQL client libraries, which have licenses that are completely independent of the PipelineDB license.

If you're using the database as a completely separate backend and simply communicating with it over the interface it exposes, then there's almost certainly no violation anywhere. That's its intended usage anyways.

Hopefully that helps clarify!

**Comment by KrishnaPG** [comment]
Thank you @derekjn Yes it indeed is very clear :+1:
