### ISSUE TITLE
Implement top-K datatype

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#996]
https://icmi.cs.ucsb.edu/research/tech_reports/reports/2005-23.pdf

**Comment by usmanm** [comment]
http://dspace.mit.edu/openaccess-disseminate/1721.1/73015

http://dmac.rutgers.edu/Workshops/WGUnifyingTheory/Slides/cormode.pdf

**Comment by metdos** [comment]
Hey @usmanm,

We started to implement an open source PostgreSQL extension for top-K using count-min sketch. It will be production quality once we are done. I wanted to let you know. So maybe you can benefit from it or use it as it is once we are done.

Here is the link to repo. It is under development currently.
https://github.com/citusdata/cms_topn

Best,
Metin

**Comment by derekjn** [comment]
Hey @metdos, CMS is overweight at not appropriate for top-k in our opinion, so we're going to go with a more special-purpose approach.

Looking at your code, a lot of it is basically copied and pasted verbatim without attribution from our code anyways, so we wouldn't benefit from using any of it.

**Comment by ozgune** [comment]
Hey @derekjn,

We'll certainly add attributions to PipelineDB. If it came across differently, that's our bad. If we miss relevant sections in a week, could you open an issue / send us an email?

I asked @metdos to post to this thread sooner rather than later (we don't even have a readme) to see if there was any value in collaborating between the two teams. Our intent with this project is to have this as an extension and make it available to the wider PostgreSQL audience.

For our customers, we found that CMS was good enough. Were you thinking of using a hybrid data structure that used different methods depending on frequencies (similar to the HyperLogLog extension)?

Best,
Ozgun

**Comment by usmanm** [comment]
Hey @metdos, I think we're going to go for a counter-based rather than sketch-based solution for top-K. Counter-based methods are much more space-efficient, which for us is pretty important. Thanks for letting us know though!
